- name: SO Update
  yum:
    name: '*'
    state: latest

- name: Install base packs
  yum:
    name: "{{ packs1 }}"
    state: latest

- name: Disable SELinux
  selinux:
    state: disabled
  ignore_errors: true

- name: Disable SELinx on source
  lineinfile:
    path: /etc/selinux/config
    regex: '^SELINUX='
    line: SELINUX=disabled
  ignore_errors: true

- name: Disable Firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: Install pip cheetah and ansible
  pip:
    name:
      - cheetah
      - ansible
    executable: pip2


